
on:
  push:
    branches: ['main']

#env:
#  REGISTRY_IMAGE: user/app
env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: nickp60/shunpyker
#  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=tag
            type=raw,value={{sha}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          flavor: |
            latest=auto
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          #tags: ${{ steps.meta.outputs.tags }}
          load: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name-canonical=true,push=true
          tags: ${{ env.REGISTRY_IMAGE }}
      # - name: run test blas
      #   run: |
      #     cmd="docker run  --rm -v $PWD:$PWD --entrypoint /opt/conda/envs/shunPykeR/bin/python $( echo  ${{ steps.meta.outputs.tags }} |cut -f 2 -d' ')  $PWD/notebooks/check-blas.py"
      #     echo $cmd
      #     $cmd
      # - name: run test integration
      #   run: |
      #     wget https://cf.10xgenomics.com/samples/cell-vdj/4.0.0/sc5p_v2_hs_PBMC_1k/sc5p_v2_hs_PBMC_1k_filtered_feature_bc_matrix.h5
      #     cmd="docker run  --rm -v $PWD:$PWD -e OPENBLAS_CORETYPE=ARCH_X86 --entrypoint /opt/conda/envs/shunPykeR/bin/python $( echo  ${{ steps.meta.outputs.tags }} |cut -f 2 -d' ')  $PWD/notebooks/gha-test.py $PWD/sc5p_v2_hs_PBMC_1k_filtered_feature_bc_matrix.h5"
      #     echo $cmd
      #     $cmd

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run test blas
        run: |
          cmd="docker run  --rm -v $PWD:$PWD --entrypoint /opt/conda/envs/shunPykeR/bin/python $( echo  ${{ steps.meta.outputs.tags }} |cut -f 2 -d' ')  $PWD/notebooks/check-blas.py"
          echo $cmd
          $cmd
      - name: run test integration
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ];
          then
          ARCH=AMD_X86
          else"
          ARCH=ARCH_X86
          fi
          wget https://cf.10xgenomics.com/samples/cell-vdj/4.0.0/sc5p_v2_hs_PBMC_1k/sc5p_v2_hs_PBMC_1k_filtered_feature_bc_matrix.h5
          cmd="docker run  --rm -v $PWD:$PWD -e OPENBLAS_CORETYPE=${ARCH}  --entrypoint /opt/conda/envs/shunPykeR/bin/python $( echo  ${{ steps.meta.outputs.tags }} |cut -f 2 -d' ')  $PWD/notebooks/gha-test.py $PWD/sc5p_v2_hs_PBMC_1k_filtered_feature_bc_matrix.h5"
          echo $cmd
          $cmd

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}





# # from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# name: Create and publish a Docker image

# on:
#   push:
#     branches: ['main']

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   build-and-push-image:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Log in to the Container registry
#         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#           tags: |
#             type=ref,event=tag
#             type=raw,value={{sha}}
#             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
#           flavor: |
#             latest=auto
#       - uses: docker/setup-qemu-action@v3
#       - uses: docker/setup-buildx-action@v3
#       - uses: docker/build-push-action@v6
#         with:
#           context: .
#           platforms: linux/amd64,linux/arm64
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
#           tags: tmp
#       - name: run test
#         run: |
#           wget https://cf.10xgenomics.com/samples/cell-vdj/4.0.0/sc5p_v2_hs_PBMC_1k/sc5p_v2_hs_PBMC_1k_filtered_feature_bc_matrix.h5
#           docker run --rm -v $PWD:$PWD tmp /opt/conda/envs/shunPykeR/bin/python $PWE/notebooks/gha-test.py $PWD/sc5p_v2_hs_PBMC_1k_filtered_feature_bc_matrix.h5
#       - uses: docker/build-push-action@v5
#         with:
#           context: .
#           platforms: linux/amd64,linux/arm64
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
#           tags: ${{ steps.meta.outputs.tags }}
#           push: true
